buyproperty/urls.py
from django.conf.urls import url
from buyproperty import views

urlpatterns = [
    url(r'^home/$', views.HomePageView.as_view(), name="property-home-page"),
    url(r'^dash/home/$', views.DashboardView.as_view(), name="property-dashboard"),
    url(r'^dash/customer-leads/$', views.CustomerLeadView.as_view(), name="property-customer-lead"),
    url(r'^dash/agent-leads/$', views.AgentLeadView.as_view(), name="property-agent-lead"),
    url(r'^dash/login/$', views.LoginView.as_view(), name="property-login"),
    url(r'^dash/properties/$', views.PropertyListView.as_view(), name="property-property-list"),
    url(r'^dash/property-create/$', views.PropertyCreateView.as_view(), name="property-property-create"),
    url(r'^dash/property-details/$', views.PropertyDetailsView.as_view(), name="property-property-details"),
]

buyproperty/urls/urls.py
from django.conf.urls import url
from buyproperty import views

urlpatterns = [
    url(r'^dash/home/$', views.DashboardView.as_view(), name="property-dashboard"),
    url(r'^get-customer-leads/$', views.CustomerLeadsAPIView.as_view(), name="list-create-customer-lead"),
    url(r'^dash/leads/$', views.CustomerLeadView.as_view(), name="property-customer-lead"),
    url(r'^dash/agent-leads/$', views.AgentLeadView.as_view(), name="property-agent-lead"),
    url(r'^dash/agent-leads/get-agent-leads/$', views.AgentLeadsAPIView.as_view(), name="property-agent-lead"),
    url(r'^dash/login/$', views.LoginView.as_view(), name="property-login"),
    url(r'^dash/logout/$', views.LogoutFlip.as_view(), name="property-logout"),
    url(r'^dash/properties/$', views.PropertyListView.as_view(), name="property-property-list"),
    url(r'^dash/property-create/$', views.PropertyCreateView.as_view(), name="property-property-create"),
    url(r'^dash/property-details/$', views.PropertyDetailsView.as_view(), name="property-property-details"),
    url(r'^dash/settings/$', views.SettingView.as_view(), name="settings"),


]

property/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^control/', include('buyproperty.urls.urls'), name="page"),
    url(r'^api/', include('buyproperty.urls.api'), name="api"),
    url(r'^', include('website.urls.urls'), name="website-page"),
    url(r'^api/real_estate/', include('website.urls.api'), name="website-api"),

]


if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buyproperty/models.py
from __future__ import unicode_literals
from django.db import models
from choices import country_choices
from django.contrib.postgres.fields import JSONField


class Address(models.Model):

    class Meta:
        verbose_name = "Address"
        verbose_name_plural = "Addresses"

    name = models.CharField(max_length=200, blank=True, null=True)
    line_1 = models.CharField(max_length=100, blank=True, null=True)
    line_2 = models.CharField(max_length=100, blank=True, null=True)
    locality = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    zip = models.CharField(max_length=6, null=True, blank=True)

    def __str__(self):
        if self.line_1 and self.name:
            return self.name + " " + self.line_1
        elif self.name:
            return self.name
        else:
            return None

    @classmethod
    def create_address(cls, data):
        address = Address.objects.create(
            name=data.get("name"),
            line_1=data.get("line_1"),
            line_2=data.get("line_2"),
            locality=data.get("locality"),
            city=data.get("city"),
            state=data.get("state"),
            country=data.get("country"),
            zip=data.get("zip")
        )
        return address


class Nearest(models.Model):
    LOCALITY_CHOICES = [
        ('bus', 'Bus Stop'),
        ('school', 'School'),
        ('mall', 'Shopping Mall'),
        ('hospital', 'Hospital'),
        ('bank', 'Bank'),
        ('atm', 'ATM'),
        ('restaurant', 'Restaurant'),
        ('metro', 'Metro Station'),
        ('train', 'Train Station'),
        ('pharmacy', 'Pharmacy')
    ]
    title = models.CharField(choices=LOCALITY_CHOICES, null=True, blank=True, max_length=20)
    nearest_description = models.TextField(blank=True, default="Nearest Place Description here.")
    distance = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.title) if self.title else "No title"

    @classmethod
    def create_nearest(cls, nearest_obj):
        nearest = Nearest.objects.create(
            title=nearest_obj.get("title"),
            nearest_description=nearest_obj.get("nearest_description"),
            distance=nearest_obj.get("distance")
        )
        return nearest


class Video(models.Model):
    TYPE_CHOICE = [
        ('b', 'Banner'),
        ('t', 'Tour')
    ]
    title = models.CharField(max_length=200, default="Video Title", blank=True)
    type = models.CharField(choices=TYPE_CHOICE, max_length=1, null=True, blank=True, default="b")
    url = models.URLField(max_length=350, null=True, blank=True)

    @classmethod
    def create_video(cls, data):
        video = Video.objects.create(
            title=data.get("title"),
            type=data.get("type"),
            url=data.get("url")
        )
        return video

    def __str__(self):
        return "Video Url "+str(self.title) if self.title else self.url


class Media(models.Model):
    TYPE_CHOICE = [
        ('b', 'Banner'),
        ('f', 'Floor Plan')
    ]
    title = models.CharField(max_length=220, null=True, blank=True, default="Media Title")
    type = models.CharField(choices=TYPE_CHOICE, null=True, blank=True, max_length=1, default="b")
    description = models.TextField(null=True, blank=True, default="Default Description")
    file = models.FileField(null=True, upload_to="files/")
    default_in_group = models.BooleanField(default=False)

    def __str__(self):
        return "Media " + str(self.id) if str(self.id) else "Media Object"

    @classmethod
    def generate_unique_key(cls, length):
        '''
        Generates a random string of a specified length.
        :param length:
        :return:
        '''
        import random, string
        return ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(length))


class FloorPlan(models.Model):
    FLOOR_CHOICES = [
        (-1, 'No Plan'),
        (0, 'Bareshell'),
        (1, 'Office Plan'),
        (2, 'Design Renders'),
        (3, 'Site Photos'),
    ]
    floor_number = models.IntegerField(choices=FLOOR_CHOICES, blank=True, null=True, help_text="floor plan")
    number_of_floor = models.IntegerField(help_text="floor number")
    description = models.TextField(blank=True, default="Floor description here")
    images = models.ManyToManyField(Media, blank=True)
    videos = models.ManyToManyField(Video, blank=True)

    @classmethod
    def create_plan(cls, number, desc, floor=0):

        plan = FloorPlan.objects.create(
            floor_number=number,
            description=desc,
            number_of_floor=floor
        )
        return plan

    def __str__(self):
        if len(self.description) != 0:
            return str(self.floor_number)+" "+str(self.description)
        else:
            return str(self.floor_number)


class Overlooking(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, default="Default")

    def __str__(self):
        return str(self.name) if self.name else None

    @classmethod
    def create_overlooking(cls, name):
        overl = Nearest.objects.create(
            name=name
        )
        return overl


class Property(models.Model):

    class Meta:
        verbose_name = 'Property'
        verbose_name_plural = "Properties"

    FURNISHING_CHOICE = [
        ('semi', 'Semi Furnished'),
        ('bare', 'Bareshell')
    ]
    PARKING_CHOICE = [
        ('cover', 'Covered'),
        ('expose', 'Exposed')
    ]
    FACING_CHOICE = [
        ('n', 'North'),
        ('ne', 'North East'),
        ('nw', 'North West'),
        ('s', 'South'),
        ('se', 'South East'),
        ('sw', 'South west'),
        ('e', 'East'),
        ('w', 'West'),
    ]
    FLOORING_CHOICE = [
        ('tile', 'Tiles'),
        ('wood', 'Wooden'),
        ('carpet', 'Carpet'),
        ('bare', 'Bare'),
    ]
    UNIT_CHOICES = [
        ('sqmt', 'Square Mt.'),
        ('sqft', 'Square Ft.')
    ]
    property_id = models.CharField(max_length=20, null=True, default=" ")
    property_name = models.CharField(blank=True, max_length=250, default=" ")
    furnishing_status = models.CharField(choices=FURNISHING_CHOICE, blank=True, null=True, max_length=30)
    unit_of_area = models.CharField(choices=UNIT_CHOICES, null=True, blank=True, max_length=20)
    buildup_area = models.FloatField(null=True, blank=True)
    carpet_area = models.FloatField(null=True, blank=True)
    rental_value = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    monthly_maintenance = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    security_deposit = models.IntegerField(blank=True, null=True)
    pantry = models.BooleanField(default=False)
    washroom = models.BooleanField(default=False)
    washroom_details = JSONField(null=True, blank=True)
    floor_num = models.PositiveIntegerField(blank=True, null=True)
    number_of_basements = models.PositiveIntegerField(blank=True, null=True)
    total_number_of_floors = models.IntegerField(blank=True, null=True)
    units_on_floor = models.PositiveIntegerField(blank=True, null=True)
    power_backup = models.BooleanField(default=False)
    parking = models.CharField(choices=PARKING_CHOICE, blank=True, null=True, max_length=6)
    lift_availability = models.BooleanField(default=False)
    landmark = models.CharField(max_length=200, null=True, blank=True, default=" ")
    parking_area = models.FloatField(blank=True, null=True)
    overlooking = models.ManyToManyField(Overlooking, blank=True)
    age = models.FloatField(null=True, blank=True)
    facing = models.CharField(choices=FACING_CHOICE, null=True, blank=True, max_length=2)
    flooring = models.CharField(choices=FLOORING_CHOICE, null=True, blank=True, max_length=6)
    a_c = models.BooleanField(default=False)
    cctv = models.BooleanField(default=False)
    cafeteria = models.BooleanField(default=False)
    fire_sprinklers = models.BooleanField(default=False)
    description = models.TextField(null=True, blank=True)
    ceiling_height = models.FloatField(blank=True, null=True)
    beam_height = models.FloatField(blank=True, null=True)
    earthing = models.BooleanField(default=False)
    electrical_con = models.BooleanField(default=False)
    flooring_details = models.TextField(blank=True, null=True)
    ceiling_details = models.TextField(blank=True, null=True)
    images = models.ManyToManyField(Media, blank=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    contact = models.CharField(max_length=10, blank=True, null=True, default=" ")
    other_charges = JSONField(null=True, blank=True)
    lease_term = models.FloatField(null=True, blank=True)
    nearest = models.ManyToManyField(Nearest, blank=True)
    country_code = models.CharField(choices=country_choices, max_length=5, null=True, blank=True)
    is_top = models.BooleanField(blank=True, default=False)
    videos = models.ManyToManyField(Video, blank=True)
    floor_plan = models.ManyToManyField(FloorPlan, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    latitude = models.CharField(max_length=100, blank=True, null=True)
    longitude = models.CharField(max_length=100, blank=True, null=True)
    map_address = models.CharField(max_length=350, blank=True, null=True)
    common_reception = models.BooleanField(default=False)
    security = models.BooleanField(default=False)
    visitor_parking = models.BooleanField(default=False)

    def __str__(self):
        if self.property_id and self.property_name:
            return str(self.property_id) + " " + str(self.property_name)
        elif self.property_name:
            return str(self.id)

    @classmethod

buyproperty/templates/dashboard/agent-leads.html
{% extends 'dashboard/base.html' %}
{% load static from staticfiles %}

{% block content %}
   <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <div class="container-fluid" id="agent-leads-app">
        <div class="row" style="margin-top: 100px"></div>
        <div class="row">
            <div class="col-md-12">
                {% if agent_leads %}
                    <table class="table table-responsive-lg table-bordered leads">
                    <thead>
                        <tr>
                            <th>Lead ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Mobile</th>
                            <th>Enquiry</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in agent_leads %}
                            <tr class="table-info odd">
                                <td><a>#{{ lead.id }}</a> </td>
                                <td>{{ lead.name }}</td>
                                <td><a href="mailto:{{ lead.email }}">{{ lead.email }}</a> </td>
                                <td>{{ lead.contact }}</td>
                                <td>{{ lead.message }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>


                {% else %}
                    <div class="alert alert-info">
                        There are currently no leads available.
                    </div>
                    <!--
                    <div class="row" style="margin-top: 30px">
                        <div class="col-md-12">
                            <button class="btn btn-xs btn-info is-line-height {% if view.get_lead_from == "0" %}disabled{% endif %}" onclick="previousRecord()" id="previous-customer-lead" {% if view.get_lead_from == "0" %}disabled{% endif %}>Previous</button>
                            <button class="btn btn-xs btn-info is-line-height disabled" style="margin-left: 20px" id="next-customer-lead" disabled>Next</button>
                        </div>
                    </div>
                    -->
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}

{% block page_level_scripts %}
    <script>
/*
        $("#next-customer-lead").on("click", function () {
            window.location =
                "/_/dash/leads/?item_from=" + (parseInt(getUrlParameter("item_from")) + 9) +
                "&item_to=" + (parseInt(getUrlParameter("item_to")) + 9);
        });
        $("#previous-customer-lead").on("click", function () {
            window.location =
                "/_/dash/leads/?item_from=" + (parseInt(getUrlParameter("item_from")) - 9) +
                "&item_to=" + (parseInt(getUrlParameter("item_to")) - 9);
        });

*/
    </script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(".leads").DataTable({
            "order": [[ 0, "asc" ]]
        });
    </script>
{% endblock %}

buyproperty/templates/dashboard/base.html
{% load static from staticfiles %}
<html>
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129703226-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-129703226-1');
        </script>
        <!-- bootstrap 4 -->
        <link href="https://bootswatch.com/4/pulse/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="{% static 'theme/css/base.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'theme/css/property_shortcuts.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'theme/css/property_theme.css' %}" rel="stylesheet" type="text/css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>
        <!-- favicon links -->
        <link rel="shortcut icon" type="image/png" href="{% static 'website-theme/images/header/favicon.png' %}" />
        {%  block scoped_css %}
        {% endblock %}
    </head>
    <body>

    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
		<div class="container-fluid">
			<a class="navbar-brand" href="/">Flip Spaces VR</a> <button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarResponsive" data-toggle="collapse" type="button"><span class="navbar-toggler-icon"></span></button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav">
					<li class="nav-item {% if view.active_tab == "home" %}active{% endif %}">
						<a class="nav-link" href="/control/dash/home/">Home</a>
					</li>
                    <li class="nav-item {% if view.active_tab == "customer-leads" %}active{% endif %}">
						<a class="nav-link" href="/control/dash/leads/">Leads</a>
					</li>
{#                    <li class="nav-item {% if view.active_tab == "agent-leads" %}active{% endif %}">#}
{#						<a class="nav-link" href="/control/dash/agent-leads/">Agent Leads</a>#}
{#					</li>#}
                    <li class="nav-item {% if view.active_tab == "properties" %}active{% endif %}">
						<a class="nav-link" href="/control/dash/properties/">Properties</a>
					</li>
				</ul>
				<ul class="nav navbar-nav ml-auto">
                    <li class="nav-item {% if view.active_tab == "property-create" %}active{% endif %}">
                        <a class="nav-link" href="../property-create">Add Property</a>
                    </li>
                    <li class="nav-item {% if view.active_tab == "settings" %}active{% endif %}">
                        <a class="nav-link" href="/control/dash/settings/">Settings</a>
                    </li>

                    <li class="nav-item">
                        {% if not request.user.is_anonymous %}
						    <a class="nav-link" href="/control/dash/logout/" id="logout-is">Log Out</a>
                        {% else %}
                            <a class="nav-link" href="/control/dash/login/" id="logout-is">Log in</a>
                        {% endif %}

					</li>
				</ul>
			</div>
		</div>
	</div>

    {% block content %}{% endblock %}
    </body>
    <footer>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="{% static 'theme/js/dash-base.js' %}"></script>
        <script src="{% static 'theme/js/shortcuts.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-growl/1.0.0/jquery.bootstrap-growl.min.js" async></script>
    </footer>

    {% block page_level_scripts %}{% endblock %}
</html>

buyproperty/templates/dashboard/customer-leads.html
{% extends 'dashboard/base.html' %}
{% load static from staticfiles %}
{% block content %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

    <div class="container-fluid">
        <div class="row" style="margin-top: 100px"></div>
        <div class="row">
            <div class="col-md-12">
                {% if leads %}
                    <table class="table table-responsive-lg table-bordered leads">
                    <thead>
                        <tr >
                            <th>Lead ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Mobile</th>
                            <th>Property ID</th>
                            <th>Message</th>
                            <th>Partner Type</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in leads %}
                            <tr class="table-info odd">
                                <td><a>#{{ lead.id }}</a></td>
                                <td>{{ lead.name }}</td>
                                <td><a href="mailto:{{ lead.email }}">{{ lead.email }}</a> </td>
                                <td>{{ lead.country_code }}{{ lead.contact }}</td>
                                <td><a href="../property-details/?p={{ lead.for_property.id }}">{{ lead.for_property.property_id }}</a></td>
                                <td>{{ lead.message }}</td>
                                <td>{{ lead.partner_type }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>


                {% else %}
                    <div class="alert alert-info">
                        There are currently no leads available.
                    </div>

{#                    <div class="row" style="margin-top: 30px">#}
{#                        <div class="col-md-12">#}
{#                            <button class="btn btn-xs btn-info is-line-height {% if view.get_lead_from == "0" %}disabled{% endif %}" onclick="previousRecord()" id="previous-customer-lead" {% if view.get_lead_from == "0" %}disabled{% endif %}>Previous</button>#}
{#                            <button class="btn btn-xs btn-info is-line-height disabled" style="margin-left: 20px" id="next-customer-lead" disabled>Next</button>#}
{#                        </div>#}
{#                    </div>#}

                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}

{% block page_level_scripts %}
    <script>
/*
        $("#next-customer-lead").on("click", function () {
            window.location =
                "/_/dash/leads/?item_from=" + (parseInt(getUrlParameter("item_from")) + 9) +
                "&item_to=" + (parseInt(getUrlParameter("item_to")) + 9);
        });
        $("#previous-customer-lead").on("click", function () {
            window.location =
                "/_/dash/leads/?item_from=" + (parseInt(getUrlParameter("item_from")) - 9) +
                "&item_to=" + (parseInt(getUrlParameter("item_to")) - 9);
        });

*/
    </script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script>
        $(".leads").DataTable({
            "order": []
        });
    </script>

{% endblock %}

buyproperty/templates/dashboard/dashboard.html
{% extends 'dashboard/base.html' %}
{% load static from staticfiles %}

{% block content %}
    <div class="container-fluid">
        <div class="row" style="margin-top: 120px"></div>
        <div class="row">
            <div class="col-md-12">
                <div class="card card-default">
                    <div class="card-body">
                        <h3>Welcome</h3>
                        <p>To get started, head over to leads.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 30px"></div>
        <div class="row">
            <div class="col-md-6">
                <div class="card card-default">
                    <div class="card-header">
                        Properties Statistics
                    </div>
                    <div class="card-body">
                        {% if counts %}
                            <h4>You have updated {{ counts.property_count }} properties in the last 7 days.</h4>
                        {% else %}
                            <h4>You have updated {{ counts }} properties in the last 7 days.</h4>
                        {% endif %}

                    </div>
                </div>
            </div>
{#            <div class="col-md-4">#}
{#                <div class="card card-default">#}
{#                    <div class="card-header">#}
{#                        Agent Leads Statistics#}
{#                    </div>#}
{#                    <div class="card-body">#}
{#                        {% if counts %}#}
{#                            <h4>You have received {{ counts.agent_lead_count }} leads in the last 24 hours.</h4>#}
{#                        {% else %}#}
{#                            <h4>You have received {{ counts }} leads in the last 24 hours.</h4>#}
{#                        {% endif %}#}
{##}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
            <div class="col-md-6">
                <div class="card card-default">
                    <div class="card-header">
                        Customer Leads Statistics
                    </div>
                    <div class="card-body">
                        {% if counts %}
                            <h4>You have received {{ counts.customer_lead_count }} leads in the last 24 hours.</h4>
                        {% else %}
                            <h4>You have received {{ counts }} leads in the last 24 hours.</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 30px"></div>
        <div class="row">
            <div class="col-md-6">
                <div class="card card-default">
                    <div class="card-body">
                        <h4>Need help?</h4>
                        <p>
                            <b>Email</b>: Flipoffice@Flipspacesvr.Com<br>
                            <b>Phone</b>: 9029049471/2
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card card-default">
                    <div class="card-body">
                        <h4>Other Resources</h4>
                        <p>
                            <b>Documentation</b>: TODO?<br>
                            <b>BigDrop</b>: https://www.bigdrop.io/
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
<script src="{% static 'theme/js/dashboard.js' %}"></script>

buyproperty/templates/dashboard/property-list.html
{% extends 'dashboard/base.html' %}
{% load static from staticfiles %}

{% block content %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <div class="container-fluid">
        <div class="row" style="margin-top: 100px"></div>
        <div class="row">
            <div class="col-md-12">
                {% if property_list %}
                    <table class="table table-responsive-lg table-bordered leads">
                    <thead>
                        <tr>
                            <th>Property ID</th>
                            <th>Title</th>
                            <th>Address</th>
                            <th>Landmark</th>
                            <th>Builtup Area</th>
                            <th>Floor Number | Total Floors</th>
                            <th>Contact</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for property in property_list %}
                            <tr class="table-info">
                                <td><a href="../property-details/?p={{ property.pk }}">#{{ property.property_id }}</a> </td>
                                {% if property.property_name %}
                                    <td>{{ property.property_name }}</td>
                                {% else %}
                                    <td>---------</td>
                                {% endif %}
                                <td>{{ property.address }} </td>
                                {% if property.landmark %}
                                    <td>{{ property.landmark }}</td>
                                {% else %}
                                    <td>--------</td>
                                {% endif %}
                                <td>{{ property.buildup_area}} {{ property.unit_of_area }}</td>
                                <td>{{ property.floor_num }} | {{ property.total_number_of_floors }} </td>
                                <td>{{ property.country_code }} {{ property.contact }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
        
    
                {% else %}
                    <div class="alert alert-info">
                        There are currently no properties available.
                    </div>
                    <div class="row" style="margin-top: 30px">
                        <div class="col-md-12">
                            <button class="btn btn-xs btn-info is-line-height {% if view.get_lead_from == "0" %}disabled{% endif %}" onclick="previousRecord()" id="previous-customer-lead" {% if view.get_lead_from == "0" %}disabled{% endif %}>Previous</button>
                            <button class="btn btn-xs btn-info is-line-height disabled" style="margin-left: 20px" id="next-customer-lead" disabled>Next</button>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}
<script src="{% static 'theme/js/property-list.js' %}"></script>
{% block page_level_scripts %}
    <script>
    /*
        $("#next-customer-lead").on("click", function () {
            window.location =
                "/_/dash/leads/?item_from=" + (parseInt(getUrlParameter("item_from")) + 9) +
                "&item_to=" + (parseInt(getUrlParameter("item_to")) + 9);
        });
        $("#previous-customer-lead").on("click", function () {
            window.location =
                "/_/dash/leads/?item_from=" + (parseInt(getUrlParameter("item_from")) - 9) +
                "&item_to=" + (parseInt(getUrlParameter("item_to")) - 9);
        });
      */
    </script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(".leads").DataTable({
            "order": []
        });
    </script>
    <script src="{%  static 'theme/js/property-list.js'   %}"></script>
{% endblock %}